### ISSUE TITLE
Would you mind releasing a new build for #1

### ISSUE THREAD

**Issue by alex-the-man** [mestevens/typesafe-dropwizard-configuration#2]
I happen to need the fix in PR #1 .

Would you mind releasing a new build to Maven Central? Thank you so much :).

**Comment by mestevens** [comment]
In the process of releasing a new build to maven central at the moment. It's been a while so I'm just figuring it out again. This should be done within the hour.

**Comment by mestevens** [comment]
I just released version 1.2 to maven central. It might take an hour to show up at most. If you're still not seeing it by then, just comment here and I'll take a look

**Comment by mestevens** [comment]
Version 1.2 has been released to maven central.

**Comment by alex-the-man** [comment]
Thank you so much Matthew.
